---
name: eliud_pkg_fundamentals
description: Package with fundamental classes to build your app
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_fundamentals
version: 1.0.1+11
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  eliud_core: ^1.0.10+1
  getwidget: ^3.0.1
  transparent_image: ^2.0.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  photo_view: ^0.14.0
  equatable: ^2.0.5
  flutter_markdown: ^0.6.13
  cloud_firestore: ^4.6.0
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  meta: ^1.8.0
  http: ^0.13.5
  collection: ^1.17.0
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.4+1
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/android.jpg
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/iphone.jpg
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/macbook.jpg
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/tablet.jpg
platforms:
  android: null
  ios: null
  web: null
