name: eliud_pkg_fundamentals
description: Package with fundamental classes to build your app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: 4.4.3
  google_sign_in_web: ^0.9.1
  cupertino_icons: ^0.1.3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  datetime_picker_formfield: ^1.0.0
  flutter_colorpicker: any
  flutter_iconpicker: any
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  cached_network_image: ^2.2.0
  expandable: 4.1.2
  font_awesome_flutter: ^8.7.0
  firebase_auth: 0.15.5+3
  carousel_slider: ^1.4.1
  getflutter: 1.0.11
  flutter_markdown: ^0.3.3
  equatable: ^1.1.1
  image_cropper: 1.2.1
  image_picker: 0.6.3+4
  image: 2.1.12
  webview_flutter: ^0.3.19+8
  vertical_tabs: ^0.2.0
  flutter_html: ^0.11.1					#DO NOT UPGRADE
  flutter_widget_from_html: 0.3.2+1		#DO NOT UPGRADE
  uuid: 2.0.4
  flare_splash_screen: 3.0.1
  chewie: 0.9.10
  video_player: 0.10.11+1
  dynamic_widget: 2.0.0
  photo_view: 0.9.2
  rxdart: ^0.24.0
  flutter_money_formatter: ^0.4.5
  http_auth: 0.2.9
  google_fonts: 1.1.0
  intl: ^0.15.6

  eliud_core:
    path: ../eliud_core

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: Tahu!
      fonts:
        - asset: assets/fonts/Tahu!.ttf
