name: eliud_pkg_fundamentals
description: Package with fundamental classes to build your app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  getwidget: ^1.1.0
  flutter_markdown: ^0.3.3
  photo_view: 0.9.2
  dynamic_widget: 3.0.1
  transparent_image: 1.0.0

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
