name: eliud_pkg_fundamentals
description: Package with fundamental classes to build your app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  getflutter: 1.0.11
  flutter_markdown: ^0.3.3
  photo_view: 0.9.2
  dynamic_widget: 2.0.0
  flutter_html: ^0.11.1					#DO NOT UPGRADE

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true
