---
name: eliud_pkg_fundamentals
description: eliud_pkg_feed is a package to provide fundamental gui components to
  your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_fundamentals
version: 1.1.7
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.1.6
  eliud_core_model: ^1.0.0
  eliud_core_main: ^1.0.2
  eliud_core_helpers: ^1.0.0
  eliud_pkg_fundamentals_model: ^1.1.7
  transparent_image: ^2.0.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  photo_view: ^0.14.0
  flutter_markdown: ^0.6.18+2
  getwidget: ^4.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/android.jpg
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/iphone.jpg
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/macbook.jpg
  - packages/eliud_pkg_fundamentals/assets/wizards/fader/tablet.jpg
platforms:
  android: null
  ios: null
  web: null
