name: eliud_pkg_fundamentals
description: Package with fundamental classes to build your app

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  getwidget: 3.0.1
  transparent_image : ^2.0.0
# dynamic_widget is currently not supported by flutter 3.1.
# dynamic_widget: ^4.0.5

dev_dependencies:
  build_runner: "2.1.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_fundamentals/assets/wizards/fader/android.jpg
    - packages/eliud_pkg_fundamentals/assets/wizards/fader/iphone.jpg
    - packages/eliud_pkg_fundamentals/assets/wizards/fader/macbook.jpg
    - packages/eliud_pkg_fundamentals/assets/wizards/fader/tablet.jpg
